import React from 'react';

export default function About() {
    return (
        <div className="about-page">
            <h1>About Me</h1>
            <h4>Sophia Rojas – Professional Nature Photographer</h4>
            <p>Hello, I’m Sophia Rojas, a professional nature photographer specializing in landscape, wildlife, and environmental photography. My mission is to capture the beauty, strength, and balance of the natural world through imagery that inspires appreciation, respect, and conservation.<br/><br/>Photography, for me, is more than an artistic pursuit — it’s a commitment to seeing and sharing the world with intention. From the quiet light of dawn over a mountain ridge to the intricate patterns of a single leaf, I strive to create photographs that remind us of our connection to nature and the importance of protecting it. Each image I create is the result of patience, preparation, and a deep respect for the environment I’m privileged to photograph.<br/><br/>My journey began with a simple love for the outdoors and a curiosity about light. Over time, that curiosity grew into a career built on technical skill, creative vision, and an unwavering dedication to quality. Today, I work with editorial publications, conservation organizations, eco-tourism groups, and private collectors, providing professional imagery that tells the story of the Earth’s remarkable diversity. Whether I’m documenting a rugged coastline, a still forest, or the motion of wildlife in its natural habitat, my goal is to produce photographs that evoke both awe and understanding.<br/><br/>Each project I take on begins with thoughtful planning — from location scouting and environmental research to understanding lighting conditions and seasonal timing. My approach combines technical precision with creative storytelling. I believe the best nature photography captures not just what the world looks like, but how it feels to stand within it. I work with both digital and drone photography, offering a range of perspectives that highlight the grandeur and intimacy of our planet’s landscapes.<br/><br/>Sustainability is at the heart of my work. I collaborate with organizations that support environmental protection and use my platform to raise awareness about the importance of preserving natural habitats. My prints and products are made using eco-friendly materials, ensuring that my work reflects the same care and respect I have for the world I photograph.<br/><br/>Beyond commercial and editorial projects, I offer fine art prints, custom commissions, and photography workshops for those who wish to explore the art and discipline of nature photography. I take pride in creating a professional yet approachable experience for every client — delivering images and services that meet the highest standards of creativity and craftsmanship.<br/><br/>Thank you for visiting my portfolio and learning more about my work. Through my lens, I aim to share the extraordinary beauty of our planet and inspire others to see nature not just as scenery, but as something worth protecting.<br/><br/></p>
            <h4>– Sophia Rojas<br/><br/>Professional Nature Photographer | Capturing the Earth’s Beauty with Purpose and Precision</h4>
        </div>
    );
}